### ISSUE TITLE
npm rebuild node-sass

### ISSUE THREAD

**Issue by wangkanai** [damienbod/AspNetCoreAngularSignalRSecurity#11]
I'm getting the following error with testing out your app, the error from google chrome console.
While it asking me to `npm rebuild node-sass`, but when i look in the package.json. I don't even see this command.

```log
index.js:1789 Uncaught Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding C:\Users\sarin\source\repos\AspNetCoreAngularSignalRSecurity\SecurityAspNetCoreSignalR\node_modules\node-sass\vendor\win32-x64-72\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (C:\Users\sarin\source\repos\AspNetCoreAngularSignalRSecurity\SecurityAspNetCoreSignalR\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Users\sarin\source\repos\AspNetCoreAngularSignalRSecurity\SecurityAspNetCoreSignalR\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\sarin\source\repos\AspNetCoreAngularSignalRSecurity\SecurityAspNetCoreSignalR\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (C:\Users\sarin\source\repos\AspNetCoreAngularSignalRSecurity\SecurityAspNetCoreSignalR\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at getDefaultSassImpl (C:\Users\sarin\source\repos\AspNetCoreAngularSignalRSecurity\SecurityAspNetCoreSignalR\node_modules\sass-loader\dist\index.js:198:10)
    at Object.loader (C:\Users\sarin\source\repos\AspNetCoreAngularSignalRSecurity\SecurityAspNetCoreSignalR\node_modules\sass-loader\dist\index.js:80:29)
    at Object../node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./angularApp/styles.scss (https://localhost:44311/dist/app.bundle.js:98497:7)
    at __webpack_require__ (https://localhost:44311/dist/app.bundle.js:20:30)
    at Object../angularApp/styles.scss (https://localhost:44311/dist/app.bundle.js:12199:15)
    at __webpack_require__ (https://localhost:44311/dist/app.bundle.js:20:30)
    at Module../angularApp/main.ts (https://localhost:44311/dist/app.bundle.js:240:14)
    at __webpack_require__ (https://localhost:44311/dist/app.bundle.js:20:30)
    at https://localhost:44311/dist/app.bundle.js:84:18
    at https://localhost:44311/dist/app.bundle.js:87:10
```
Maybe to better to understand the enviroment
```console
PS C:\> npm -v
6.13.4
PS C:\> node -v
v12.4.0
PS C:\> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.1.1
Node: 12.4.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.1
@angular-devkit/core         8.1.1
@angular-devkit/schematics   8.1.1
@schematics/angular          8.1.1
@schematics/update           0.801.1
rxjs                         6.4.0
```

**Comment by wangkanai** [comment]
I have downgrade node & npm, but i still get the same result.
```console
nvm install 12
12.0.0
Downloading node.js version 12.0.0 (64-bit)...
Complete
Creating C:\Users\sarin\AppData\Roaming\nvm\temp

Downloading npm version 6.9.0... Complete
Installing npm v6.9.0...

Installation complete. If you want to use this version, type

nvm use 12.0.0
```

**Comment by damienbod** [comment]
fixed, thanks for reporting
